import { Component, OnInit } from '@angular/core';
import { Orienteerer } from '../orienteerer';
import { OrienteererService } from '../orienteerer.service';
import { Sex, Specialty, SkillLevel} from '../constants';

@Component({
  selector: 'app-orienteerers',
  templateUrl: './orienteerers.component.html',
  styleUrls: ['./orienteerers.component.css']
})
export class OrienteerersComponent implements OnInit {

  orienteerers: Orienteerer[];

  dummyOrienteerer = {
    //id: undefined, // will be generated by in memory data service
    firstName: 'Temppi',
    lastName: 'Temppi',
    nickName: '',
    sex: Sex.Male,
    nationality: 'Finnish',
    endurance: SkillLevel.titanic,
    strength: SkillLevel.titanic,
    speed: SkillLevel.titanic,
    mapReading: SkillLevel.titanic,
    consistency: SkillLevel.titanic,
    concentration: SkillLevel.titanic,
    routeChoosing: SkillLevel.titanic,
    finishing: SkillLevel.titanic,
    nightSkills: SkillLevel.titanic,
    specialty: Specialty.None
  };

  constructor(private orienteererService: OrienteererService) {
   }

  ngOnInit() {
    this.getOrienteerers();
  }

  getOrienteerers(): void {
    this.orienteererService.getOrienteerers()
      .subscribe(orienteerers => this.orienteerers = orienteerers);
  }

  add(): void {
    this.orienteererService.addOrienteerer(this.dummyOrienteerer as Orienteerer)
      .subscribe(orienteerer => {
        this.orienteerers.push(orienteerer);
    });
  }

}
